spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/laptop-website
    username: postgres
    password: hoang2003

    driver-class-name: org.postgresql.Driver
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com

    port: 25
    username: <gmail>
    password: <password>

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: <key>

api:
  endpoint: <endpoint to frontend>

email:

  sender: <gmail>

