spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/laptop-website
    username: postgres
    password: hiepbui32
    driver-class-name: org.postgresql.Driver
  jpa:

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "bR/S8KVi0SkB02p/4tlq81tEhbZGTJ8aNmlOEHZE2+Yb5uhVlPzmRFrY1AOSXnz/"