spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/laptop-website
    #    username: postgres
    #    password: hoang2003
    url: jdbc:postgresql://dpg-cp8m56f109ks739t70m0-a.singapore-postgres.render.com:5432/laptop_website_db
    username: admin
    password: gHyoF7VN5E2EJUYUod1n0ry1nO8XU3bO
    driver-class-name: org.postgresql.Driver
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ok.byethibye2@gmail.com
    password: uwikbacvdxedubkm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "bR/S8KVi0SkB02p/4tlq81tEhbZGTJ8aNmlOEHZE2+Yb5uhVlPzmRFrY1AOSXnz/"

api:
  endpoint: "http://localhost:3000"

email:
  sender: ok.byethibye2@gmail.com